# Day 3 - Create Batches for Transforming Historical Price with Summary

In [22]:
import os
import json
from dotenv import load_dotenv
from huggingface_hub import login
import numpy as np
import pandas as pd
import yfinance as yf
import matplotlib.pyplot as plt
from datasets import load_dataset, Dataset, DatasetDict
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from openai import OpenAI
from litellm import completion
from tqdm.notebook import tqdm
from IPython.display import display, Markdown
from pricer.evaluator import evaluate

In [23]:
load_dotenv(override=True)

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")

In [24]:
openai = OpenAI(api_key=OPENAI_API_KEY)

In [25]:
MODEL = "gpt-4.1-nano"

In [10]:
processed_df = pd.read_csv("dfs/processed_stock_data.csv")

In [104]:
train = processed_df[(processed_df['End Date'] >= '2002-01-01') & (processed_df['End Date'] < '2021-01-01')]
val   = processed_df[(processed_df['End Date'] >= '2021-01-01') & (processed_df['End Date'] < '2023-01-01')]
test  = processed_df[processed_df['End Date'] >= '2023-01-01']

In [163]:
for name, split in [("Train", train), ("Val", val), ("Test", test)]:
    returns = split["Return %"].astype(float)
    up = (returns > 0).mean()
    print(f"\n{name}: {len(split)} samples")
    print(f"  UP: {up:.1%}, DOWN: {1-up:.1%}")
    print(f"  Mean: {returns.mean():.2f}%")
    print(f"  Std:  {returns.std():.2f}%")
    print(f"  Min:  {returns.min():.2f}%")
    print(f"  Max:  {returns.max():.2f}%")

Train: 7129 samples
  UP: 47.0%, DOWN: 53.0%
  Mean: 0.66%
  Std:  13.03%
  Min:  -66.61%
  Max:  237.77%

Val: 1377 samples
  UP: 52.4%, DOWN: 47.6%
  Mean: 2.36%
  Std:  17.30%
  Min:  -39.16%
  Max:  211.63%

Test: 3933 samples
  UP: 51.2%, DOWN: 48.8%
  Mean: 1.98%
  Std:  12.22%
  Min:  -44.32%
  Max:  84.62%

In [164]:
print(f"Train: {len(train)} samples, Val: {len(val)} samples, Test: {len(test)} samples")

Train: 7129 samples, Val: 1377 samples, Test: 3933 samples

In [15]:
processed_df.iloc[0]["Price History"]

'Date: 2006-07-10 00:00:00, Close: 494.30, Volume: 54632458, MA-200: 412.44, MA-150: 456.88, MA-50: 475.27, Momentum-10: 0.11, RSI-14: 67.65\nDate: 2006-07-11 00:00:00, Close: 499.64, Volume: 59436161, MA-200: 413.61, MA-150: 457.72, MA-50: 473.52, Momentum-10: 0.07, RSI-14: 67.65\nDate: 2006-07-12 00:00:00, Close: 491.63, Volume: 78261085, MA-200: 414.67, MA-150: 458.68, MA-50: 471.40, Momentum-10: 0.02, RSI-14: 63.77\nDate: 2006-07-13 00:00:00, Close: 488.95, Volume: 21164273, MA-200: 415.67, MA-150: 459.71, MA-50: 469.43, Momentum-10: 0.01, RSI-14: 63.77\nDate: 2006-07-14 00:00:00, Close: 486.28, Volume: 41435665, MA-200: 416.64, MA-150: 460.75, MA-50: 467.41, Momentum-10: -0.02, RSI-14: 61.76\nDate: 2006-07-17 00:00:00, Close: 478.27, Volume: 16351641, MA-200: 417.55, MA-150: 461.60, MA-50: 465.54, Momentum-10: -0.05, RSI-14: 53.23\nDate: 2006-07-18 00:00:00, Close: 478.27, Volume: 16559980, MA-200: 418.52, MA-150: 462.46, MA-50: 463.98, Momentum-10: -0.10, RSI-14: 48.21\nDate: 2006-07-19 00:00:00, Close: 478.27, Volume: 0, MA-200: 419.46, MA-150: 463.38, MA-50: 462.11, Momentum-10: -0.10, RSI-14: 47.27\nDate: 2006-07-20 00:00:00, Close: 488.95, Volume: 52778240, MA-200: 420.48, MA-150: 464.39, MA-50: 460.24, Momentum-10: 0.02, RSI-14: 48.21\nDate: 2006-07-21 00:00:00, Close: 478.27, Volume: 17580841, MA-200: 421.44, MA-150: 465.28, MA-50: 458.27, Momentum-10: 0.01, RSI-14: 42.11\nDate: 2006-07-24 00:00:00, Close: 496.97, Volume: 43590487, MA-200: 422.48, MA-150: 466.29, MA-50: 457.91, Momentum-10: 0.01, RSI-14: 37.74\nDate: 2006-07-25 00:00:00, Close: 507.66, Volume: 53397304, MA-200: 423.57, MA-150: 467.30, MA-50: 457.75, Momentum-10: 0.02, RSI-14: 42.86\nDate: 2006-07-26 00:00:00, Close: 507.66, Volume: 0, MA-200: 424.65, MA-150: 468.25, MA-50: 457.09, Momentum-10: 0.03, RSI-14: 63.16\nDate: 2006-07-27 00:00:00, Close: 507.66, Volume: 0, MA-200: 425.73, MA-150: 469.18, MA-50: 456.42, Momentum-10: 0.04, RSI-14: 66.67\nDate: 2006-07-28 00:00:00, Close: 545.06, Volume: 26024526, MA-200: 427.02, MA-150: 470.36, MA-50: 456.51, Momentum-10: 0.12, RSI-14: 72.09\nDate: 2006-07-31 00:00:00, Close: 555.75, Volume: 39795739, MA-200: 428.38, MA-150: 471.59, MA-50: 459.43, Momentum-10: 0.16, RSI-14: 73.33\nDate: 2006-08-01 00:00:00, Close: 555.75, Volume: 23572078, MA-200: 429.74, MA-150: 472.87, MA-50: 462.30, Momentum-10: 0.16, RSI-14: 78.57\nDate: 2006-08-02 00:00:00, Close: 555.75, Volume: 19923168, MA-200: 431.10, MA-150: 474.03, MA-50: 465.02, Momentum-10: 0.16, RSI-14: 80.49\nDate: 2006-08-03 00:00:00, Close: 545.06, Volume: 17554055, MA-200: 432.45, MA-150: 475.01, MA-50: 467.52, Momentum-10: 0.11, RSI-14: 75.00\nDate: 2006-08-04 00:00:00, Close: 539.72, Volume: 10780058, MA-200: 433.77, MA-150: 475.87, MA-50: 469.92, Momentum-10: 0.13, RSI-14: 76.74\nDate: 2006-08-07 00:00:00, Close: 550.41, Volume: 21955962, MA-200: 435.13, MA-150: 476.62, MA-50: 472.53, Momentum-10: 0.11, RSI-14: 78.72\nDate: 2006-08-08 00:00:00, Close: 555.75, Volume: 7143054, MA-200: 436.56, MA-150: 477.41, MA-50: 474.22, Momentum-10: 0.09, RSI-14: 79.59\nDate: 2006-08-09 00:00:00, Close: 550.41, Volume: 5098354, MA-200: 438.00, MA-150: 478.21, MA-50: 476.06, Momentum-10: 0.08, RSI-14: 74.47\nDate: 2006-08-10 00:00:00, Close: 545.06, Volume: 30724061, MA-200: 439.39, MA-150: 478.74, MA-50: 478.25, Momentum-10: 0.07, RSI-14: 77.78\nDate: 2006-08-11 00:00:00, Close: 555.75, Volume: 9524072, MA-200: 440.86, MA-150: 479.32, MA-50: 480.61, Momentum-10: 0.02, RSI-14: 76.19\nDate: 2006-08-14 00:00:00, Close: 571.78, Volume: 10946730, MA-200: 442.40, MA-150: 479.92, MA-50: 483.18, Momentum-10: 0.03, RSI-14: 77.27\nDate: 2006-08-15 00:00:00, Close: 577.13, Volume: 39804668, MA-200: 443.98, MA-150: 480.66, MA-50: 486.18, Momentum-10: 0.04, RSI-14: 78.26\nDate: 2006-08-16 00:00:00, Close: 571.78, Volume: 7821644, MA-200: 445.52, MA-150: 481.55, MA-50: 489.57, Momentum-10: 0.03, RSI-14: 75.00\nDate: 2006-08-17 00:00:00, Close: 571.78, Volume: 0, MA-200: 447.09, MA-150: 482.29, MA-50: 493.33, Momentum-10: 0.05, RSI-14: 64.71\nDate: 2006-08-18 00:00:00, Close: 571.78, Volume: 0, MA-200: 448.69, MA-150: 482.99, MA-50: 496.89, Momentum-10: 0.06, RSI-14: 60.00'

In [26]:
SYSTEM_PROMPT = """You are a quantitative financial analyst. You will receive 30 days of historical stock data including: closing price, volume, MA-200, MA-150, MA-50, 10-day momentum, and 14-day RSI. Your job is to produce a structured summary that captures the information most predictive of price movement over the next 7 days. Be concise and signal-focused — avoid restating raw numbers unless they mark a key level. Output your summary in this exact format:
TREND: [Bullish / Bearish / Neutral] — one sentence on the dominant short-term price trend.
MOMENTUM: One sentence on momentum and RSI trajectory (accelerating, fading, reversing).
MA_STRUCTURE: One sentence on price position relative to MA-50, MA-150, MA-200 (above/below, converging/diverging).
VOLUME: One sentence on recent volume patterns and what they suggest about short-term conviction.
KEY_LEVELS: Comma-separated near-term support and resistance levels — these will be used as price targets.
RISK_FACTORS: One sentence on the biggest short-term uncertainty or warning sign in the data.
PREDICTION_CONTEXT: One sentence stating the expected direction (UP or DOWN), the primary price target, and the extended range if momentum continues. 
Example UP: "UP — expect price to test resistance at [level] within 7 days, with further upside to [level] if buying pressure sustains."
Example DOWN: "DOWN — expect price to test support at [level] within 7 days, with downside risk to [level] if selling pressure continues."
"""

In [ ]:
messages = [
    {"role": "system", "content": SYSTEM_PROMPT},
    {"role": "user", "content": processed_df.iloc[18]["Price History"]},
]

response = completion(model="gpt-4.1-nano", messages=messages)

print(f"Input tokens: {response.usage.prompt_tokens}")
print(f"Output tokens: {response.usage.completion_tokens}")
print(f"Total cost: {response._hidden_params["response_cost"]*100:.4f} cents")

Input tokens: 2659
Output tokens: 246
Total cost: 0.0364 cents

In [125]:
display(Markdown(f"**Model Response:**\n\n{response.choices[0].message.content}"))

**Model Response:**

TREND: Bearish — price has drifted lower into early January after failing to sustain the mid-December rebound.
MOMENTUM: 10-day momentum has turned negative again and RSI has dropped from the low-50s to low-30s, signaling weakening and possible continuation of the selloff.
MA_STRUCTURE: Close is below MA-50 and far below the still-rising MA-150 and MA-200, with moving averages diverging downward away from price (overhead resistance).
VOLUME: The latest leg down (notably 2023-01-04 to 2023-01-05) came with heavier volume, suggesting conviction behind bearish pressure rather than a low-volume drift.
KEY_LEVELS: 1500 support, 1450 support, 1620 resistance (near MA-50 area), 1650 resistance, 1710 resistance (near MA-200 region)
RISK_FACTORS: RSI is nearing oversold territory, so a sharp mean-reversion bounce is plausible even if the dominant 7-day bias remains down.
PREDICTION_CONTEXT: DOWN — expect a retest of support at ~1500 within 7 days, with downside risk to ~1450 if selling pressure persists; if momentum stabilizes, a relief bounce may cap near ~1620 (MA-50).

In [17]:
def make_jsonl(row):
    body = {"model": MODEL, "messages": [{"role": "system", "content": SYSTEM_PROMPT}, {"role": "user", "content": row["Price History"]}]}
    line = {"custom_id": str(row["Id"]), "method": "POST", "url": "/v1/chat/completions", "body": body}
    return json.dumps(line)

In [18]:
make_jsonl(processed_df.iloc[0])

'{"custom_id": "8899", "method": "POST", "url": "/v1/chat/completions", "body": {"model": "gpt-4.1-nano", "messages": [{"role": "system", "content": "You are a quantitative financial analyst. You will receive 30 days of historical stock data including: closing price, volume, MA-200, MA-150, MA-50, 10-day momentum, and 14-day RSI. Your job is to produce a structured summary that captures the information most predictive of price movement over the next 7 days. Be concise and signal-focused \\u2014 avoid restating raw numbers unless they mark a key level. Output your summary in this exact format:\\nTREND: [Bullish / Bearish / Neutral] \\u2014 one sentence on the dominant short-term price trend.\\nMOMENTUM: One sentence on momentum and RSI trajectory (accelerating, fading, reversing).\\nMA_STRUCTURE: One sentence on price position relative to MA-50, MA-150, MA-200 (above/below, converging/diverging).\\nVOLUME: One sentence on recent volume patterns and what they suggest about short-term conviction.\\nKEY_LEVELS: Comma-separated near-term support and resistance levels \\u2014 these will be used as price targets.\\nRISK_FACTORS: One sentence on the biggest short-term uncertainty or warning sign in the data.\\nPREDICTION_CONTEXT: One sentence stating the expected direction (UP or DOWN), the primary price target, and the extended range if momentum continues. \\nExample UP: \\"UP \\u2014 expect price to test resistance at [level] within 7 days, with further upside to [level] if buying pressure sustains.\\"\\nExample DOWN: \\"DOWN \\u2014 expect price to test support at [level] within 7 days, with downside risk to [level] if selling pressure continues.\\"\\n"}, {"role": "user", "content": "Date: 2006-07-10 00:00:00, Close: 494.30, Volume: 54632458, MA-200: 412.44, MA-150: 456.88, MA-50: 475.27, Momentum-10: 0.11, RSI-14: 67.65\\nDate: 2006-07-11 00:00:00, Close: 499.64, Volume: 59436161, MA-200: 413.61, MA-150: 457.72, MA-50: 473.52, Momentum-10: 0.07, RSI-14: 67.65\\nDate: 2006-07-12 00:00:00, Close: 491.63, Volume: 78261085, MA-200: 414.67, MA-150: 458.68, MA-50: 471.40, Momentum-10: 0.02, RSI-14: 63.77\\nDate: 2006-07-13 00:00:00, Close: 488.95, Volume: 21164273, MA-200: 415.67, MA-150: 459.71, MA-50: 469.43, Momentum-10: 0.01, RSI-14: 63.77\\nDate: 2006-07-14 00:00:00, Close: 486.28, Volume: 41435665, MA-200: 416.64, MA-150: 460.75, MA-50: 467.41, Momentum-10: -0.02, RSI-14: 61.76\\nDate: 2006-07-17 00:00:00, Close: 478.27, Volume: 16351641, MA-200: 417.55, MA-150: 461.60, MA-50: 465.54, Momentum-10: -0.05, RSI-14: 53.23\\nDate: 2006-07-18 00:00:00, Close: 478.27, Volume: 16559980, MA-200: 418.52, MA-150: 462.46, MA-50: 463.98, Momentum-10: -0.10, RSI-14: 48.21\\nDate: 2006-07-19 00:00:00, Close: 478.27, Volume: 0, MA-200: 419.46, MA-150: 463.38, MA-50: 462.11, Momentum-10: -0.10, RSI-14: 47.27\\nDate: 2006-07-20 00:00:00, Close: 488.95, Volume: 52778240, MA-200: 420.48, MA-150: 464.39, MA-50: 460.24, Momentum-10: 0.02, RSI-14: 48.21\\nDate: 2006-07-21 00:00:00, Close: 478.27, Volume: 17580841, MA-200: 421.44, MA-150: 465.28, MA-50: 458.27, Momentum-10: 0.01, RSI-14: 42.11\\nDate: 2006-07-24 00:00:00, Close: 496.97, Volume: 43590487, MA-200: 422.48, MA-150: 466.29, MA-50: 457.91, Momentum-10: 0.01, RSI-14: 37.74\\nDate: 2006-07-25 00:00:00, Close: 507.66, Volume: 53397304, MA-200: 423.57, MA-150: 467.30, MA-50: 457.75, Momentum-10: 0.02, RSI-14: 42.86\\nDate: 2006-07-26 00:00:00, Close: 507.66, Volume: 0, MA-200: 424.65, MA-150: 468.25, MA-50: 457.09, Momentum-10: 0.03, RSI-14: 63.16\\nDate: 2006-07-27 00:00:00, Close: 507.66, Volume: 0, MA-200: 425.73, MA-150: 469.18, MA-50: 456.42, Momentum-10: 0.04, RSI-14: 66.67\\nDate: 2006-07-28 00:00:00, Close: 545.06, Volume: 26024526, MA-200: 427.02, MA-150: 470.36, MA-50: 456.51, Momentum-10: 0.12, RSI-14: 72.09\\nDate: 2006-07-31 00:00:00, Close: 555.75, Volume: 39795739, MA-200: 428.38, MA-150: 471.59, MA-50: 459.43, Momentum-10: 0.16, RSI-14: 73.33\\nDate: 2006-08-01 00:00:00, Close: 555.75, Volume: 23572078, MA-200: 429.74, MA-150: 472.87, MA-50: 462.30, Momentum-10: 0.16, RSI-14: 78.57\\nDate: 2006-08-02 00:00:00, Close: 555.75, Volume: 19923168, MA-200: 431.10, MA-150: 474.03, MA-50: 465.02, Momentum-10: 0.16, RSI-14: 80.49\\nDate: 2006-08-03 00:00:00, Close: 545.06, Volume: 17554055, MA-200: 432.45, MA-150: 475.01, MA-50: 467.52, Momentum-10: 0.11, RSI-14: 75.00\\nDate: 2006-08-04 00:00:00, Close: 539.72, Volume: 10780058, MA-200: 433.77, MA-150: 475.87, MA-50: 469.92, Momentum-10: 0.13, RSI-14: 76.74\\nDate: 2006-08-07 00:00:00, Close: 550.41, Volume: 21955962, MA-200: 435.13, MA-150: 476.62, MA-50: 472.53, Momentum-10: 0.11, RSI-14: 78.72\\nDate: 2006-08-08 00:00:00, Close: 555.75, Volume: 7143054, MA-200: 436.56, MA-150: 477.41, MA-50: 474.22, Momentum-10: 0.09, RSI-14: 79.59\\nDate: 2006-08-09 00:00:00, Close: 550.41, Volume: 5098354, MA-200: 438.00, MA-150: 478.21, MA-50: 476.06, Momentum-10: 0.08, RSI-14: 74.47\\nDate: 2006-08-10 00:00:00, Close: 545.06, Volume: 30724061, MA-200: 439.39, MA-150: 478.74, MA-50: 478.25, Momentum-10: 0.07, RSI-14: 77.78\\nDate: 2006-08-11 00:00:00, Close: 555.75, Volume: 9524072, MA-200: 440.86, MA-150: 479.32, MA-50: 480.61, Momentum-10: 0.02, RSI-14: 76.19\\nDate: 2006-08-14 00:00:00, Close: 571.78, Volume: 10946730, MA-200: 442.40, MA-150: 479.92, MA-50: 483.18, Momentum-10: 0.03, RSI-14: 77.27\\nDate: 2006-08-15 00:00:00, Close: 577.13, Volume: 39804668, MA-200: 443.98, MA-150: 480.66, MA-50: 486.18, Momentum-10: 0.04, RSI-14: 78.26\\nDate: 2006-08-16 00:00:00, Close: 571.78, Volume: 7821644, MA-200: 445.52, MA-150: 481.55, MA-50: 489.57, Momentum-10: 0.03, RSI-14: 75.00\\nDate: 2006-08-17 00:00:00, Close: 571.78, Volume: 0, MA-200: 447.09, MA-150: 482.29, MA-50: 493.33, Momentum-10: 0.05, RSI-14: 64.71\\nDate: 2006-08-18 00:00:00, Close: 571.78, Volume: 0, MA-200: 448.69, MA-150: 482.99, MA-50: 496.89, Momentum-10: 0.06, RSI-14: 60.00"}]}}'

In [19]:
def make_file(start, end, filename):
    batch_file = filename
    with open(batch_file, "w", encoding="utf-8") as f:
        for i in range(start, end):
            jsonl = make_jsonl(processed_df.iloc[i])
            f.write(jsonl + "\n")

In [27]:
make_file(3000, 3500, "jsonl/batches-3/3000_3500.jsonl")

In [79]:
with open("jsonl/batches-3/3000_3500.jsonl", "rb") as f:
    response = openai.files.create(file=f, purpose="batch")
response

FileObject(id='file-GRHPeGC316Z4ccSo7xCKbG', bytes=3034181, created_at=1778509808, filename='3000_3500.jsonl', object='file', purpose='batch', status='processed', expires_at=1781101808, status_details=None)

In [80]:
batch = openai.batches.create(completion_window="24h", endpoint="/v1/chat/completions", input_file_id=response.id)

In [81]:
result = openai.batches.retrieve(batch.id)

In [82]:
result

Batch(id='batch_6a01e7f1ba24819098802046759903d7', completion_window='24h', created_at=1778509809, endpoint='/v1/chat/completions', input_file_id='file-GRHPeGC316Z4ccSo7xCKbG', object='batch', status='completed', cancelled_at=None, cancelling_at=None, completed_at=1778510020, error_file_id=None, errors=None, expired_at=None, expires_at=1778596209, failed_at=None, finalizing_at=1778509999, in_progress_at=1778509814, metadata=None, model='gpt-4.1-nano-2025-04-14', output_file_id='file-Ar8g2aW2dF5DswgbqwEyq5', request_counts=BatchRequestCounts(completed=500, failed=0, total=500), usage=BatchUsage(input_tokens=1353500, input_tokens_details=InputTokensDetails(cached_tokens=0), output_tokens=106303, output_tokens_details=OutputTokensDetails(reasoning_tokens=0), total_tokens=1459803))

In [83]:
response = openai.files.content(result.output_file_id)
response.write_to_file("jsonl/outputs-3/3000_3500.jsonl")

In [153]:
for start in tqdm(range(0, 3500, 500)):
    end = min(start + 500, 3500)
    with open(f"jsonl/outputs-3/{start}_{end}.jsonl", "r", encoding="utf-8") as f:
        for line in f:
            json_line = json.loads(line)
            id = int(json_line["custom_id"])
            summary = json_line["response"]["body"]["choices"][0]["message"]["content"]
            processed_df.loc[processed_df["Id"] == id, "Price History"] = summary
        f.close()

  0%|          | 0/7 [00:00<?, ?it/s]

In [141]:
print(f"5 sample summaries:\n")
for i in range(5):
    print(processed_df.iloc[i]["Price History"])

5 sample summaries:

TREND: Neutral — despite recent rebound attempts, the stock remains largely range-bound with a weak short-term trend.

MOMENTUM: Momentum has faded from positive highs and is now moderate; RSI shows overbought conditions earlier but has declined under 70, indicating weakening near-term strength.

MA_STRUCTURE: Price oscillates around the MA-50 and remains below the rising MA-200 and MA-150, suggesting medium-term bearish relevance; recent flattening indicates potential consolidation.

VOLUME: Recent volume spikes on upward moves suggest sporadic buying interest, but overall low volume during some declines points to cautious or uncertain conviction.

KEY_LEVELS: Support near 545, Resistance at 577

RISK_FACTORS: Widening divergence between short-term momentum and longer-term moving averages introduces uncertainty about sustained upside.

PREDICTION_CONTEXT: DOWN — expect price to test support at 545 within 7 days, with downside potential to 535 if selling increases.
TREND: Neutral — despite recent gains, the stock remains well above long-term moving averages, but lacks clear directional momentum.

MOMENTUM: The 10-day momentum is fading but remains slightly positive; RSI has peaked around 80 and then declined, indicating waning near-term buying pressure.

MA_STRUCTURE: Price is above all key MAs (50, 150, 200), but the gap is narrowing as shorter-term MAs flatten and longer-term MAs continue to rise.

VOLUME: Recent volume spikes during upward moves suggest short-term trading conviction, but declining volume during sideways phases indicates caution among traders.

KEY_LEVELS: Support near 545, resistance at 570, with potential upside test at 580 if momentum re-accelerates.

RISK_FACTORS: The fading momentum and declining RSI suggest weakening buying conviction, posing a risk of short-term pullback.

PREDICTION_CONTEXT: DOWN — expect price to test support at 545 within 7 days, with downside potential to 535 if selling pressure intensifies.
TREND: Bullish — the stock has demonstrated strong upward movement, trading well above all major MAs, indicating sustained positive momentum.

MOMENTUM: Momentum shows signs of accelerating with recent gains and rising RSI, suggesting increasing buying pressure; the RSI is near overbought levels but still climbing.

MA_STRUCTURE: Price remains above the MA-50, MA-150, and MA-200, with these averages diverging upward, confirming a robust uptrend.

VOLUME: Recent volume spikes, especially on upward moves, reflect strong conviction backing the rally and short-term buying interest.

KEY_LEVELS: Support at 560, Resistance at 630.

RISK_FACTORS: Overbought RSI and overextension above key averages pose a short-term risk of a correction or consolidation phase.

PREDICTION_CONTEXT: UP — expect price to test resistance at 630 within 7 days, with further upside potential to around 650 if momentum sustains.
TREND: Bullish — the stock remains in a strong uptrend with prices well above all major moving averages and recent sharp gains indicating sustained upward momentum.
MOMENTUM: Momentum has accelerated sharply over the past few days, with the 10-day momentum turning positive and RSI climbing into overbought territory, suggesting strong buying pressure but potential near-term exhaustion.
MA_STRUCTURE: Price is significantly above the MA-50, MA-150, and MA-200, which are all diverging further upward, confirming a robust bullish structure.
VOLUME: Volume has surged notably on the recent upward moves, especially on the latest breakout days, indicating high conviction among buyers.
KEY_LEVELS: Support at 545, resistance at 630
RISK_FACTORS: Overbought RSI and momentum levels pose a risk of short-term pullback or consolidation.
PREDICTION_CONTEXT: UP — expect price to test resistance at 630 within 7 days, with further upside to 650 if buying pressure sustains and momentum maintains its strength.
TREND: Bullish — the stock has shown strong upward movement with prices surpassing the key moving averages and continuing recent gains.
MOMENTUM: Momentum remains positive but shows signs of fading slightly from peak levels; RSI indicates overbought conditions at 65–80, suggesting possible short-term fatigue but no immediate reversal.
MA_STRUCTURE: Price is well above all major MAs (50, 150, 200) with some divergence, confirming a bullish trend, though recent price was at or near historical highs.
VOLUME: Recent volume surged significantly on the latest breakout days, indicating strong buy conviction but also warning of potential exhaustion or reversal at these elevated levels.
KEY_LEVELS: Support near 540, resistance at 630
RISK_FACTORS: Overbought RSI and high volume on breakout days increase risk of short-term pullback or consolidation.
PREDICTION_CONTEXT: UP — expect price to test resistance at 630 within 7 days, with further upside to around 650 if buying pressure sustains and momentum remains intact.

In [161]:
processed_df.to_csv("dfs/processed_stock_data_with_summaries.csv", index=False)

In [11]:
processed_df = pd.read_csv("dfs/processed_stock_data_with_summaries.csv")

In [12]:
processed_df = processed_df[processed_df["Ticker"].isin(["ADMR.JK", "PTRO.JK", "PANI.JK", "BUMI.JK", "BRMS.JK", "ANTM.JK"])]

In [13]:
processed_df

,Id,Ticker,Start Date,End Date,Future Date,Last Price,Price History,Future Price,Return %
0,0,ADMR.JK,2022-10-27,2022-12-07,2022-12-16,1530.52,TREND: Bearish — the stock has been declining ...,1600.09,4.55
1,1,ADMR.JK,2022-10-28,2022-12-08,2022-12-19,1558.35,TREND: Bearish — the recent downward trend per...,1576.90,1.19
2,2,ADMR.JK,2022-10-31,2022-12-09,2022-12-20,1549.08,TREND: Bearish — the overall direction has bee...,1525.89,-1.50
3,3,ADMR.JK,2022-11-02,2022-12-13,2022-12-22,1553.71,TREND: Bearish — the stock has largely decline...,1595.46,2.69
4,4,ADMR.JK,2022-11-04,2022-12-15,2022-12-26,1576.90,TREND: Bearish — the price remains below all m...,1539.80,-2.35
...,...,...,...,...,...,...,...,...,...
12394,12394,ANTM.JK,2025-12-29,2026-02-11,2026-02-24,3990.00,"TREND: Neutral — after recent volatility, the ...",4380.00,9.77
12395,12395,ANTM.JK,2025-12-30,2026-02-12,2026-02-25,4120.00,TREND: Bullish — the stock has experienced str...,4460.00,8.25
12396,12396,ANTM.JK,2026-01-02,2026-02-13,2026-02-26,4050.00,TREND: Neutral — after a strong upward move pe...,4330.00,6.91
12397,12397,ANTM.JK,2026-01-05,2026-02-18,2026-02-27,4050.00,"TREND: Bearish — after reaching recent highs, ...",4350.00,7.41
12398,12398,ANTM.JK,2026-01-06,2026-02-19,2026-03-02,4230.00,"TREND: Neutral — after a sharp upward move, th...",4610.00,8.98

In [14]:
processed_df.iloc[0]

Id                                                               0
Ticker                                                     ADMR.JK
Start Date                                              2022-10-27
End Date                                                2022-12-07
Future Date                                             2022-12-16
Last Price                                                 1530.52
Price History    TREND: Bearish — the stock has been declining ...
Future Price                                               1600.09
Return %                                                      4.55
Name: 0, dtype: object

In [15]:
processed_df.drop(columns=["Id"], inplace=True)

In [16]:
processed_df

,Ticker,Start Date,End Date,Future Date,Last Price,Price History,Future Price,Return %
0,ADMR.JK,2022-10-27,2022-12-07,2022-12-16,1530.52,TREND: Bearish — the stock has been declining ...,1600.09,4.55
1,ADMR.JK,2022-10-28,2022-12-08,2022-12-19,1558.35,TREND: Bearish — the recent downward trend per...,1576.90,1.19
2,ADMR.JK,2022-10-31,2022-12-09,2022-12-20,1549.08,TREND: Bearish — the overall direction has bee...,1525.89,-1.50
3,ADMR.JK,2022-11-02,2022-12-13,2022-12-22,1553.71,TREND: Bearish — the stock has largely decline...,1595.46,2.69
4,ADMR.JK,2022-11-04,2022-12-15,2022-12-26,1576.90,TREND: Bearish — the price remains below all m...,1539.80,-2.35
...,...,...,...,...,...,...,...,...
12394,ANTM.JK,2025-12-29,2026-02-11,2026-02-24,3990.00,"TREND: Neutral — after recent volatility, the ...",4380.00,9.77
12395,ANTM.JK,2025-12-30,2026-02-12,2026-02-25,4120.00,TREND: Bullish — the stock has experienced str...,4460.00,8.25
12396,ANTM.JK,2026-01-02,2026-02-13,2026-02-26,4050.00,TREND: Neutral — after a strong upward move pe...,4330.00,6.91
12397,ANTM.JK,2026-01-05,2026-02-18,2026-02-27,4050.00,"TREND: Bearish — after reaching recent highs, ...",4350.00,7.41
12398,ANTM.JK,2026-01-06,2026-02-19,2026-03-02,4230.00,"TREND: Neutral — after a sharp upward move, th...",4610.00,8.98

In [17]:
train = processed_df[(processed_df['End Date'] >= '2002-01-01') & (processed_df['End Date'] < '2021-01-01')].reset_index(drop=True)
val   = processed_df[(processed_df['End Date'] >= '2021-01-01') & (processed_df['End Date'] < '2023-01-01')].reset_index(drop=True)
test  = processed_df[processed_df['End Date'] >= '2023-01-01'].reset_index(drop=True)

In [18]:
print(f"Train size: {len(train)}, Val size: {len(val)}, Test size: {len(test)}")

Train size: 7129, Val size: 1377, Test size: 3893

In [19]:
train_tickers = set(train['Ticker'].unique())
test_tickers  = set(test['Ticker'].unique())

unseen = test_tickers - train_tickers
print(f"Unseen tickers: {unseen}")
print(f"Tickers in test but never in train: {len(unseen)} / {len(test_tickers)}")
print(f"That's {len(unseen)/len(test_tickers)*100:.1f}% of test tickers unseen")

Unseen tickers: {'ADMR.JK', 'PANI.JK'}
Tickers in test but never in train: 2 / 6
That's 33.3% of test tickers unseen

In [20]:
print(f"Train size: {len(train)}, Val size: {len(val)}, Test size: {len(test)}")

Train size: 7129, Val size: 1377, Test size: 3893

In [21]:
DatasetDict({
    'train': Dataset.from_pandas(train),
    'validation': Dataset.from_pandas(val),
    'test': Dataset.from_pandas(test)
}).push_to_hub("matthewyn/stocks")

Setting num_proc from 1 back to 1 for the train split to disable multiprocessing as it only contains one shard.

Uploading the dataset shards:   0%|          | 0/1 [00:00<?, ? shards/s]

Creating parquet from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Processing Files (0 / 0): |          |  0.00B /  0.00B

New Data Upload: |          |  0.00B /  0.00B

Setting num_proc from 1 back to 1 for the validation split to disable multiprocessing as it only contains one shard.

Uploading the dataset shards:   0%|          | 0/1 [00:00<?, ? shards/s]

Creating parquet from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Processing Files (0 / 0): |          |  0.00B /  0.00B

New Data Upload: |          |  0.00B /  0.00B

Setting num_proc from 1 back to 1 for the test split to disable multiprocessing as it only contains one shard.

Uploading the dataset shards:   0%|          | 0/1 [00:00<?, ? shards/s]

Creating parquet from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Processing Files (0 / 0): |          |  0.00B /  0.00B

New Data Upload: |          |  0.00B /  0.00B

No files have been modified since last commit. Skipping to prevent empty commit.

CommitInfo(commit_url='https://huggingface.co/datasets/matthewyn/stocks/commit/c775d11ece29a97047dfe8450a1fd87d5cae2b53', commit_message='Upload dataset', commit_description='', oid='c775d11ece29a97047dfe8450a1fd87d5cae2b53', pr_url=None, repo_url=RepoUrl('https://huggingface.co/datasets/matthewyn/stocks', endpoint='https://huggingface.co', repo_type='dataset', repo_id='matthewyn/stocks'), pr_revision=None, pr_num=None)